---

- name: R | APT key (CRAN)
  tags:
  - apt
  apt_key:
    keyserver: keys.gnupg.net
    id: "{{ R_cran_key }}"

- name: R | repository (CRAN)
  tags:
  - apt
  apt_repository:
    repo: "{{ R_cran_repo }}"
    filename: 'cran'

- name: R | Install packages
  tags:
  - package
  package:
    name: 
      - r-base-dev
      - libopenblas-base
      - r-cran-littler

- name: R | additional R packages
  tags:
    - package
  command: "{{ R_installer }} -r {{ R_cran_mirror }} {{ R_packages | join(' ') }}"
