---

- name: R | APT key (CRAN)
  tags:
  - apt
  get_url:
    url: "{{ R_cran_keyurl }}"
    dest: "{{ R_cran_keyring }}"

- name: R | repository (CRAN)
  tags:
  - apt
  apt_repository:
    repo: "{{ R_cran_repo }}"
    filename: 'cran'

- name: R | Install base packages
  tags:
  - package
  package:
    name: 
    - libopenblas-dev
    - r-base-dev
    state: latest

- name: R | Install additional system packages
  tags:
  - package
  package:
    name: "{{ R_sys_pkgs }}"
    state: latest

- name: R | system-wide config /etc/R/
  tags:
  - config
  copy:
    content: "{{ item.value }}"
    dest: /etc/R/{{ item.key }}
  loop: "{{ R_etc_R | dict2items }}"

- name: R | install R packages
  tags:
  - package
  command: R -q -e 'install.packages("{{ item }}", quiet = TRUE)'
  args:
    creates: "{{ R_libloc ~ item }}"
  loop: "{{ R_pkgs }}"

