---

- name: R | APT key (CRAN)
  tags:
  - apt
  apt_key:
    keyserver: keys.gnupg.net
    id: "{{ R_cran_key }}"

- name: R | repository (CRAN)
  tags:
  - apt
  apt_repository:
    repo: "{{ R_cran_repo }}"
    filename: 'cran'

- name: R | Install packages
  tags:
  - package
  package:
    name: "{{ R_base_pkgs + R_prereq_pkgs }}"
    state: latest

- name: R | littler config
  tags:
    - config
  template:
    src: little.r.j2
    dest: /etc/littler.r

- name: R | install R packages
  tags:
    - package
  command: "{{ R_installer }} {{ item }}"
  args:
    creates: "{{ R_libloc ~ item }}"
  loop: "{{ R_pkgs }}"

- name: R | install R packages from github
  tags:
    - package
  command: "{{ R_github_installer }} {{ item }}"
  args:
    creates: "{{ R_libloc ~ item }}"
  loop: "{{ R_github_pkgs }}"

- name: R | update R packages
  tags:
    - update
  command: "{{ R_updater }}"

