---

- name: R | APT key (CRAN)
  tags:
  - apt
  get_url:
    url: "{{ R_cran_keyurl }}"
    dest: "{{ R_cran_keyring }}"

- name: R | repository (CRAN)
  tags:
  - apt
  apt_repository:
    repo: "{{ R_cran_repo }}"
    filename: 'cran'

- name: R | Install system packages
  tags:
  - package
  package:
    name: 
    - libopenblas-dev
    - r-base-dev
    - "{{ R_sys_pkgs }}"
    state: latest

- name: R | install R packages
  tags:
  - package
  command: R -e 'install.packages(\"{{ item }}\")'
  args:
    creates: "{{ R_libloc ~ item }}"
  loop: "{{ R_pkgs }}"

